"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import ApplicationForm from "../components/ApplicationForm";

const countries = ["Италия","Финляндия","Испания","Германия","Франция","Чехия","Греция","Польша","Венгрия","Литва","Латвия","Австрия","Португалия","Болгария","Швеция","Швейцария","Бельгия","Дания","Нидерланды","Норвегия","Эстония","Ирландия","Китай","Япония","Южная Корея"];
const photos = [
  "https://avatars.mds.yandex.net/get-altay/17637863/2a0000019c669dfc607d71279ab8b7c2625b/orig",
  "https://avatars.mds.yandex.net/get-altay/18140291/2a0000019c6f642009f1dd72cd2c3665f869/XXL_height",
  "https://avatars.mds.yandex.net/get-altay/18111128/2a0000019c669814a8294c3839199ba1cf8a/XXL_height",
];
const reviews = [
 {name:"Инна М.",date:"27 мая 2025",text:"Хочу сказать слова благодарности специалисту по работе с визами Великобритании, Варваре. Свою работу знает отлично, очень внимательная и доброжелательная.",rating:5},
 {name:"Ольга Шлосс",date:"28 августа 2025",text:"Дочь обращалась и осталась недовольна качеством обслуживания. По мнению автора, сделку не сопровождали и не сообщили об изменениях в требованиях.",rating:2},
 {name:"Ярик Яроки",date:"3 марта 2026",text:"Отличный центр. Персонал приятен в общении и отвечает на вопросы. Остался очень доволен.",rating:5},
];

const Icon=({name}:{name:"visa"|"passport"|"shield"|"copy"})=>{const paths={visa:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 9h4M7 13h7M16 9h1"/></>,passport:<><rect x="5" y="3" width="14" height="18" rx="2"/><circle cx="12" cy="11" r="3"/><path d="M9 11h6M12 8v6"/></>,shield:<><path d="M12 3 20 6v5c0 5-3.4 8.2-8 10-4.6-1.8-8-5-8-10V6l8-3Z"/><path d="m9 12 2 2 4-4"/></>,copy:<><rect x="7" y="7" width="13" height="13" rx="2"/><path d="M4 16V6a2 2 0 0 1 2-2h10"/></>};return <svg className="service-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true">{paths[name]}</svg>};

export default function Home() {
 const pathname=usePathname(); const pagesBase=pathname.startsWith("/GLOBAL")?"/GLOBAL":"";
 const [menu,setMenu]=useState(false); const [modal,setModal]=useState<string|null>(null); const [scrolled,setScrolled]=useState(false); const [query,setQuery]=useState(""); const [showAll,setShowAll]=useState(false); const [quickOpen,setQuickOpen]=useState(false);
 const phone="+7 (913) 787-18-05";
 useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>32);onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
 useEffect(()=>{document.body.style.overflow=menu||modal?"hidden":"";return()=>{document.body.style.overflow=""}},[menu,modal]);
 const filtered=useMemo(()=>countries.filter(c=>c.toLowerCase().includes(query.toLowerCase())),[query]); const shown=showAll||query?filtered:filtered.slice(0,12);
 const schema={"@context":"https://schema.org","@type":"ProfessionalService","name":"GLOBAL","description":"Сервисно-визовый центр","telephone":"+79137871805","email":"global.novosibirsk@mail.ru","url":"https://svc-global.ru","address":{"@type":"PostalAddress","streetAddress":"ул. Челюскинцев, 15Б, 1 этаж","addressLocality":"Новосибирск","postalCode":"630132","addressCountry":"RU"},"geo":{"@type":"GeoCoordinates","latitude":55.039855,"longitude":82.905859},"openingHours":"Mo-Fr 08:30-15:30","sameAs":["https://2gis.ru/novosibirsk/firm/141265770283147","https://yandex.ru/maps/org/global/1780859090/"]};
 return <>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} />
 <header className={`header ${scrolled?"header-scrolled":""}`}><div className="container header-inner"><a className="logo" href="#top">GLO<span>BAL</span></a><nav className="nav"><a href="#top">Главная</a><a href="#services">Услуги</a><a href="#countries">Страны</a><a href="#about">О компании</a><a href="#reviews">Отзывы</a><a href="#contacts">Контакты</a></nav><div className="header-actions"><a className="phone" href="tel:+79137871805">{phone}</a><a className="btn btn-dark" href="#request">Получить консультацию</a><button className={`burger ${menu?"active":""}`} aria-label={menu?"Закрыть меню":"Открыть меню"} aria-expanded={menu} onClick={()=>setMenu(!menu)}><span/><span/><span/></button></div></div></header>
 <div className={`menu-backdrop ${menu?"open":""}`} onClick={()=>setMenu(false)}/><aside className={`mobile-menu ${menu?"open":""}`} aria-hidden={!menu}><div className="mobile-menu-head"><span className="logo">GLO<span>BAL</span></span><button aria-label="Закрыть меню" onClick={()=>setMenu(false)}>×</button></div><nav>{[["Главная","top"],["Услуги","services"],["Страны","countries"],["О компании","about"],["Отзывы","reviews"],["Контакты","contacts"]].map(([x,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{x}<span>→</span></a>)}</nav><div className="mobile-menu-actions"><a href="tel:+79137871805">{phone}</a><a className="btn btn-primary" href="#request" onClick={()=>setMenu(false)}>Получить консультацию</a></div></aside>
 <main>
 <section id="top" className="hero"><div className="container hero-grid"><div className="reveal"><div className="eyebrow" style={{color:"#b8c9c1"}}>Сервисно-визовый центр · Новосибирск</div><h1>Визы без лишних сложностей</h1><p>Помогаем подготовить документы и пройти процесс оформления визы — от первичной консультации до подачи. Требования и сроки уточняем для вашей страны и ситуации.</p><div className="hero-actions"><a href="#request" className="btn btn-primary">Получить консультацию</a><a href="#services" className="btn btn-outline">Наши услуги</a></div></div><div className="hero-media"><img src={photos[0]} alt="Офис сервисно-визового центра GLOBAL"/><div className="hero-badge"><strong>4,8</strong>рейтинг в 2ГИС<br/><small>31 отзыв · 65 оценок</small></div></div></div></section>
 <div className="trustbar"><div className="container trust-items"><span><i/>25 направлений в 2ГИС</span><span><i/>Офис в центре</span><span><i/>Онлайн-услуги</span><span><i/>Пн–Пт 08:30–15:30</span></div></div>
 <section id="services" className="section"><div className="container"><div className="eyebrow">Что мы делаем</div><h2 className="h2">Помощь на каждом этапе подготовки</h2><div className="services-grid">
 {[['visa','01','Оформление виз','Консультация и подготовка комплекта документов по требованиям выбранного направления.'],['passport','02','Загранпаспорта и миграционные услуги','Помощь с документами в рамках услуг, указанных в карточке организации. Детали уточняются на консультации.'],['shield','03','Страхование для поездки','Оформление страхования выезжающих за рубеж.'],['copy','04','Фото и копировальные услуги','Фото на документы и копировальные услуги доступны в офисе GLOBAL.']].map(s=><article className="card service" key={s[1]}><div className="service-top"><Icon name={s[0] as "visa"|"passport"|"shield"|"copy"}/><span className="service-index">{s[1]}</span></div><div><h3>{s[2]}</h3><p>{s[3]}</p><a className="service-link" href="#request">Оставить заявку →</a></div></article>)}</div></div></section>
 <section id="countries" className="section directions"><div className="container"><div className="eyebrow">Популярные направления</div><h2 className="h2">Страны, указанные в карточке GLOBAL</h2><div className="country-feature"><article className="card country"><div className="flag">🇪🇺</div><div><h3>Шенген</h3><p>Подготовка визовых документов — 7 000 ₽.</p><a href="#request">Получить консультацию →</a></div></article><article className="card country"><div className="flag">🇯🇵</div><div><h3>Япония</h3><p>Услуга оформления визы — 8 000 ₽.</p><a href="#request">Получить консультацию →</a></div></article><article className="card country"><div className="flag">🇰🇷</div><div><h3>Южная Корея</h3><p>Электронная виза — 6 000 ₽.</p><a href="#request">Получить консультацию →</a></div></article></div><div className="country-tools"><label><span className="sr-only">Поиск страны</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти страну…"/></label><span>{filtered.length} направлений</span></div><div className="chips">{shown.map(c=><a className="chip" key={c} href="#request">{c}<span>→</span></a>)}</div>{!query&&<button className="btn btn-outline country-more" onClick={()=>setShowAll(!showAll)}>{showAll?"Свернуть список":"Показать все направления"}</button>}<p style={{color:"#65716b",marginTop:22}}>Стоимость услуги указана по данным Яндекс Карт. Консульские и дополнительные сборы могут рассчитываться отдельно.</p></div></section>
 <section className="section"><div className="container"><div className="eyebrow">Порядок работы</div><h2 className="h2">Понятный процесс без необоснованных обещаний</h2><div className="steps">{[['01','Заявка','Оставляете контакты и кратко описываете поездку.'],['02','Консультация','Уточняем направление, цель и исходные данные.'],['03','Проверка ситуации','Определяем применимые требования и комплект документов.'],['04','Подготовка документов','Помогаем сформировать пакет в рамках выбранной услуги.'],['05','Сопровождение подачи','Объясняем дальнейшие действия без обещаний решения консульства.']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
 <section id="about" className="section dark"><div className="container advantages"><div><div className="eyebrow">Почему GLOBAL</div><h2 className="h2">Факты вместо громких обещаний</h2><p style={{color:"#b6c5be",lineHeight:1.8,maxWidth:540,marginTop:25}}>GLOBAL работает по адресу ул. Челюскинцев, 15Б, на первом этаже. В карточках организации подтверждены визовая помощь, страхование, фото и копировальные услуги, онлайн-обслуживание и несколько способов оплаты.</p></div><div className="metrics"><div className="metric"><strong>4,8</strong><span>рейтинг в 2ГИС</span></div><div className="metric"><strong>31</strong><span>отзыв в 2ГИС</span></div><div className="metric"><strong>600 м</strong><span>до метро «Площадь Гарина-Михайловского» по Яндекс Картам</span></div><div className="metric"><strong>5</strong><span>способов оплаты указано в 2ГИС</span></div></div></div></section>
 <section id="reviews" className="section"><div className="container"><div className="reviews-head"><div><div className="eyebrow">Отзывы</div><h2 className="h2">Реальные мнения клиентов</h2></div><div><a className="btn btn-outline" href="https://2gis.ru/novosibirsk/firm/141265770283147/tab/reviews" target="_blank">Отзывы в 2ГИС</a> <a className="btn btn-outline" href="https://yandex.ru/maps/org/global/1780859090/reviews/" target="_blank">Яндекс Карты</a></div></div><div className="reviews">{reviews.map(r=><article className="card review" key={r.name}><div className="stars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</div><blockquote>«{r.text}»</blockquote><cite>{r.name}</cite><small>{r.date} · Яндекс Карты</small></article>)}</div></div></section>
 <section className="section directions"><div className="container"><div className="eyebrow">Фотографии</div><h2 className="h2">GLOBAL в Новосибирске</h2><div className="gallery">{photos.map((p,i)=><button key={p} onClick={()=>setModal(p)} aria-label={`Открыть фотографию ${i+1}`}><img src={p} alt={`Фотография офиса GLOBAL ${i+1}`} loading={i?"lazy":"eager"}/><span>Открыть ↗</span></button>)}</div><p style={{fontSize:12,color:"#758179"}}>Фотографии из карточки организации на Яндекс Картах.</p></div></section>
 <section className="section"><div className="container faq-grid"><div><div className="eyebrow">FAQ</div><h2 className="h2">Перед обращением</h2></div><div>{[['Какие документы нужны?','Перечень зависит от страны, типа визы, цели поездки и ситуации заявителя. Специалист уточнит требования после консультации.'],['Сколько занимает оформление?','Срок зависит от направления, сезона и работы консульства. GLOBAL не гарантирует решение или фиксированный срок рассмотрения.'],['Можно обратиться без готового пакета документов?','Да, начать можно с консультации и оценки вашей ситуации.'],['Как записаться?','Позвоните, напишите в WhatsApp либо заполните форму на сайте.'],['Где находится офис?','Новосибирск, ул. Челюскинцев, 15Б, 1 этаж. Ближайшее метро — «Площадь Гарина-Михайловского».']].map(x=><details key={x[0]}><summary>{x[0]}</summary><p>{x[1]}</p></details>)}</div></div></section>
 <section id="request" className="section lead"><div className="container lead-grid"><div><div className="eyebrow">Заявка</div><h2 className="h2">Получите консультацию специалиста</h2><p style={{lineHeight:1.8,maxWidth:500}}>Заполните форму — заявка будет сохранена и передана менеджеру GLOBAL через защищённый API.</p></div><ApplicationForm preset={{source:"website-main"}}/></div></section>
 <section id="contacts" className="section"><div className="container contacts"><div className="contact-card"><div className="eyebrow" style={{color:"#aebeb6"}}>Контакты</div><h2 style={{fontSize:42,letterSpacing:"-.05em"}}>Ждём вас в офисе</h2><div className="contact-row"><span>Адрес</span><strong>Новосибирск, ул. Челюскинцев, 15Б, 1 этаж</strong></div><div className="contact-row"><span>Телефон</span><strong><a href="tel:+79137871805">{phone}</a></strong></div><div className="contact-row"><span>Режим работы</span><strong>Пн–Пт: 08:30–15:30</strong></div><div className="contact-row"><span>Email</span><strong><a href="mailto:global.novosibirsk@mail.ru">global.novosibirsk@mail.ru</a></strong></div><div className="contact-actions"><a className="btn btn-primary" href="https://wa.me/79137871805" target="_blank">WhatsApp</a><a className="btn btn-outline" href="tel:+79137871805" style={{color:"white",borderColor:"#587166"}}>Позвонить</a><a className="btn btn-outline" href="https://yandex.ru/maps/?rtext=~55.039855,82.905859&rtt=auto" target="_blank" style={{color:"white",borderColor:"#587166"}}>Маршрут</a></div></div><iframe className="map" title="GLOBAL на карте" src="https://yandex.ru/map-widget/v1/?ll=82.905859%2C55.039855&z=16&pt=82.905859%2C55.039855,pm2rdm" loading="lazy"/></div></section>
 </main>
 <footer className="footer"><div className="container"><div className="footer-grid"><div><div className="logo">GLO<span>BAL</span></div><p>Сервисно-визовый центр<br/>ИП Красюк Н.А.</p></div><div><h4>Навигация</h4><a href="#services">Услуги</a><a href="#countries">Страны</a><a href="#reviews">Отзывы</a><a href="#contacts">Контакты</a></div><div><h4>Услуги</h4><a href="#services">Оформление виз</a><a href="#services">Страхование</a><a href="#services">Фото на документы</a><a href="#services">Копировальные услуги</a></div><div><h4>Связь</h4><a href="tel:+79137871805">{phone}</a><a href="mailto:global.novosibirsk@mail.ru">global.novosibirsk@mail.ru</a><p>Пн–Пт: 08:30–15:30</p></div></div><div className="footer-bottom"><span>© 2026 GLOBAL. Все права защищены.</span><span><Link href={`${pagesBase}/privacy/`}>Политика конфиденциальности</Link> · <Link href={`${pagesBase}/consent/`}>Согласие на обработку данных</Link></span></div></div></footer>
 <div className={`quick-contact ${quickOpen?"open":""}`}><div className="quick-menu"><a href="https://wa.me/79137871805" target="_blank" rel="noreferrer">WhatsApp</a><a href="tel:+79137871805">Позвонить</a></div><button onClick={()=>setQuickOpen(!quickOpen)} aria-label="Быстрая связь" aria-expanded={quickOpen}>{quickOpen?"×":"↗"}</button></div><div className="mobile-cta"><a href="tel:+79137871805">Позвонить</a><a href="https://wa.me/79137871805" target="_blank" rel="noreferrer">Написать</a><a href="#request">Заявка</a></div>
 {modal&&<div className="modal" onClick={()=>setModal(null)}><button aria-label="Закрыть">×</button><img src={modal} alt="GLOBAL крупным планом"/></div>}
 </>;
}
