import { FormEvent, useState } from "react";

export type LeadPreset={country?:string;purpose?:string;service?:string;source?:string};
const API=process.env.NEXT_PUBLIC_APPLICATIONS_API_URL||"";

export default function ApplicationForm({preset={},onSuccess}:{preset?:LeadPreset;onSuccess?:(id:string)=>void}){
 const[status,setStatus]=useState<"idle"|"loading"|"success"|"error">("idle"),[message,setMessage]=useState(""),[id,setId]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setStatus("loading");setMessage("");
  const payload={name:data.get("name"),phone:data.get("phone"),country:data.get("country"),purpose:data.get("purpose"),service:data.get("service"),comment:data.get("comment"),source:data.get("source")||preset.source||"website",consent:data.get("consent")==="on",website:data.get("website")};
  try{if(!API)throw new Error("API URL не настроен");const response=await fetch(API+"/applications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Ошибка отправки");setId(result.id);setStatus("success");form.reset();onSuccess?.(result.id)}catch(error){setStatus("error");setMessage(error instanceof Error?error.message:"Не удалось отправить заявку")}}
 return <form className="form" onSubmit={submit} noValidate><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/><input type="hidden" name="source" value={preset.source||"website"}/><div className="field"><label htmlFor="lead-name">Имя *</label><input id="lead-name" name="name" required autoComplete="name"/></div><div className="field"><label htmlFor="lead-phone">Телефон *</label><input id="lead-phone" name="phone" required inputMode="tel" placeholder="+7 (___) ___-__-__" autoComplete="tel"/></div><div className="field"><label htmlFor="lead-country">Страна *</label><input id="lead-country" name="country" required defaultValue={preset.country}/></div><div className="field"><label htmlFor="lead-purpose">Цель поездки</label><select id="lead-purpose" name="purpose" defaultValue={preset.purpose||"Туризм"}><option>Туризм</option><option>Бизнес</option><option>Учёба</option><option>Гости</option><option>Другое</option></select></div><div className="field full"><label htmlFor="lead-service">Услуга</label><input id="lead-service" name="service" defaultValue={preset.service}/></div><div className="field full"><label htmlFor="lead-comment">Комментарий</label><textarea id="lead-comment" name="comment" rows={4}/></div><label className="checkbox"><input type="checkbox" name="consent" required/>Я согласен(на) на обработку персональных данных</label><button className="btn btn-dark full" disabled={status==="loading"}>{status==="loading"?"Отправляем...":"Получить консультацию"}</button>{status==="success"&&<div className="success full" role="status"><b>✓ Заявка отправлена</b><br/>Спасибо! Специалист GLOBAL свяжется с вами.<br/>Номер заявки: #{id}</div>}{status==="error"&&<div className="form-notice full" role="alert"><b>Не удалось отправить заявку.</b><br/>{message}. Попробуйте ещё раз или свяжитесь с нами по телефону.</div>}</form>}
